USE [WorksSp]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_WorksSp_MainStock_GetById] (@MainStockId INT)
AS
BEGIN
	SELECT TOP 1 * FROM [dbo].[WorksSp_MainStock]
		WHERE MainStockId = @MainStockId;
	SET NOCOUNT ON;
END
GO
